######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 16 00:35:21 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += webkit

# Input
SOURCES += a.cpp saveData.cpp
HEADERS += saveData.h
